version: '3'
services:
    web:
    # intel
      # build: .
    # arm
      image: image-name

      container_name: my-jupyter-lab
      ports:
        - '8888:8888'
      volumes:
        - '.:/work'